// ĐÂY LÀ VÍ DỤ VỀ CODE SẼ ĐƯỢC GENERATE TỰ ĐỘNG
// Khi bạn có class RemoteData với [RemoteConfigField] attributes
// Source Generator sẽ tạo ra code như sau:

// <auto-generated />
// Generated for: RemoteData
// Total fields: 2
using System;
#if VIRTUESKY_FIREBASE_REMOTECONFIG
using Firebase.RemoteConfig;
#endif

namespace VirtueSky.RemoteConfigGenerated
{
    public static partial class RemoteData
    {
#if VIRTUESKY_FIREBASE_REMOTECONFIG
        public static int InterTimeGap
        {
            get
            {
                try
                {
                    return (int)FirebaseRemoteConfig.DefaultInstance.GetValue("inter_time_gap").DoubleValue;
                }
                catch (Exception e)
                {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                    UnityEngine.Debug.LogWarning($"Failed to get remote value for 'inter_time_gap', return default value: {e.Message}");
#endif
                    return 30;
                }
            }
        }
#else
        public static int InterTimeGap = 30;
#endif

#if VIRTUESKY_FIREBASE_REMOTECONFIG
        public static int StartLevelShowInter
        {
            get
            {
                try
                {
                    return (int)FirebaseRemoteConfig.DefaultInstance.GetValue("start_level_show_inter").DoubleValue;
                }
                catch (Exception e)
                {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                    UnityEngine.Debug.LogWarning($"Failed to get remote value for 'start_level_show_inter', return default value: {e.Message}");
#endif
                    return 15;
                }
            }
        }
#else
        public static int StartLevelShowInter = 15;
#endif

    }
}

// CÁCH SỬ DỤNG:
// Bây giờ bạn chỉ cần gọi:
// int value = RemoteData.NumRewardedLife;
// 
// Property này sẽ tự động:
// - Lấy giá trị từ Firebase Remote Config khi có VIRTUESKY_FIREBASE_REMOTECONFIG
// - Return default value khi có lỗi
// - Sử dụng field thông thường khi không có Firebase
