using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RemoteConfigGenerator
{
    [Generator]
    public class RemoteConfigSourceGenerator : ISourceGenerator
    {
        private const string AttributeNamespace = "RemoteConfigGenerator";
        private const string RemoteConfigDataAttributeName = "RemoteConfigDataAttribute";
        private const string RemoteConfigFieldAttributeName = "RemoteConfigFieldAttribute";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new RemoteConfigSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // ✅ Generate attributes first so they're available for user code
            context.AddSource("RemoteConfigAttributes.g.cs", SourceText.From(@"
using System;

namespace RemoteConfigGenerator
{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class RemoteConfigDataAttribute : Attribute
    {
        public string PrefsPrefix { get; set; } = ""rc_"";
    }

    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false)]
    public sealed class RemoteConfigFieldAttribute : Attribute
    {
        public string Key { get; set; }
        public bool PersistToPrefs { get; set; } = true;
        public bool SyncFromRemote { get; set; } = true;

        public RemoteConfigFieldAttribute() { }
        public RemoteConfigFieldAttribute(string key) { Key = key; }
    }
}
", Encoding.UTF8));

            if (!(context.SyntaxReceiver is RemoteConfigSyntaxReceiver receiver))
                return;

            foreach (var candidateClass in receiver.CandidateClasses)
            {
                var model = context.Compilation.GetSemanticModel(candidateClass.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(candidateClass);

                if (classSymbol == null)
                    continue;

                // Check if class has RemoteConfigData attribute
                var hasAttribute = classSymbol.GetAttributes()
                    .Any(a => a.AttributeClass?.Name == RemoteConfigDataAttributeName);

                if (!hasAttribute)
                    continue;

                var source = GenerateRemoteConfigExtensions(classSymbol, context);
                context.AddSource($"{classSymbol.Name}_Generated.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private string GenerateRemoteConfigExtensions(INamedTypeSymbol classSymbol, GeneratorExecutionContext context)
        {
            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            var className = classSymbol.Name;

            // Collect all fields with RemoteConfigField attribute
            var members = new List<ConfigMember>();

            foreach (var member in classSymbol.GetMembers())
            {
                var attribute = member.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == RemoteConfigFieldAttributeName);

                if (attribute == null)
                    continue;

                ConfigMember configMember = null;

                if (member is IFieldSymbol field)
                {
                    configMember = new ConfigMember
                    {
                        Name = field.Name,
                        Type = field.Type.ToDisplayString()
                    };
                }

                if (configMember != null)
                {
                    // Get Key from attribute
                    var customKey = GetAttributePropertyValue(attribute, "Key") as string;
                    if (!string.IsNullOrEmpty(customKey))
                    {
                        configMember.Key = customKey;
                    }
                    else
                    {
                        var syntaxKey = GetAttributeKeyFromSyntax(member);
                        if (!string.IsNullOrEmpty(syntaxKey))
                            configMember.Key = syntaxKey;
                        else
                            configMember.Key = configMember.Name;
                    }

                    members.Add(configMember);
                }
            }

            var sb = new StringBuilder();

            // File header
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"// Generated for: {className}");
            sb.AppendLine($"// Total fields: {members.Count}");
            sb.AppendLine("using System;");
            sb.AppendLine("#if VIRTUESKY_FIREBASE_REMOTECONFIG");
            sb.AppendLine("using Firebase.RemoteConfig;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            // Generate new static class with properties
            var configClassName = className + "Config";
            sb.AppendLine($"    public static class {configClassName}");
            sb.AppendLine("    {");

            // Generate properties for each field
            foreach (var member in members)
            {
                GenerateRemoteProperty(sb, member, className);
                sb.AppendLine();
            }

            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private void GenerateRemoteProperty(StringBuilder sb, ConfigMember member, string originalClassName)
        {
            var typeName = member.Type;
            var propertyName = member.Name;
            var remoteKey = member.Key;

            sb.AppendLine("#if VIRTUESKY_FIREBASE_REMOTECONFIG");
            sb.AppendLine($"        public static {typeName} {propertyName}");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");

            // Generate appropriate Firebase Remote Config access based on type
            if (typeName == "string" || typeName == "System.String")
            {
                sb.AppendLine($"                    return FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").StringValue;");
            }
            else if (typeName == "int" || typeName == "System.Int32")
            {
                sb.AppendLine($"                    return (int)FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").DoubleValue;");
            }
            else if (typeName == "float" || typeName == "System.Single")
            {
                sb.AppendLine($"                    return (float)FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").DoubleValue;");
            }
            else if (typeName == "double" || typeName == "System.Double")
            {
                sb.AppendLine($"                    return FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").DoubleValue;");
            }
            else if (typeName == "bool" || typeName == "System.Boolean")
            {
                sb.AppendLine($"                    return FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").BooleanValue;");
            }
            else if (typeName == "long" || typeName == "System.Int64")
            {
                sb.AppendLine($"                    return FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").LongValue;");
            }
            else
            {
                // Default to string for unknown types
                sb.AppendLine($"                    return FirebaseRemoteConfig.DefaultInstance.GetValue(\"{remoteKey}\").StringValue;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("                catch (Exception e)");
            sb.AppendLine("                {");
            sb.AppendLine("#if UNITY_EDITOR || DEVELOPMENT_BUILD");
            sb.AppendLine($"                    UnityEngine.Debug.LogWarning($\"Failed to get remote value for '{remoteKey}', return default value: {{e.Message}}\");");
            sb.AppendLine("#endif");
            sb.AppendLine($"                    return {originalClassName}.{propertyName};");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("#else");
            sb.AppendLine($"        public static {typeName} {propertyName} => {originalClassName}.{propertyName};");
            sb.AppendLine("#endif");
        }

        private string GetPrefsPrefix(INamedTypeSymbol classSymbol)
        {
            var attribute = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == RemoteConfigDataAttributeName);

            if (attribute != null)
            {
                var prefix = GetAttributePropertyValue(attribute, "PrefsPrefix") as string;
                if (!string.IsNullOrEmpty(prefix))
                    return prefix;
            }

            return "rc_";
        }

        private object GetAttributePropertyValue(AttributeData attribute, string propertyName)
        {
            // Check named arguments (e.g., Key = "value")
            foreach (var namedArg in attribute.NamedArguments)
            {
                if (namedArg.Key == propertyName)
                    return namedArg.Value.Value;
            }

            // Check constructor arguments for "Key" property specifically
            if (propertyName == "Key" && attribute.ConstructorArguments.Length > 0)
            {
                return attribute.ConstructorArguments[0].Value;
            }

            return null;
        }

        /// <summary>
        /// Parse attribute Key directly from syntax tree (fallback when semantic model doesn't work)
        /// Handles: [RemoteConfigField(Key = "VALUE")] and [RemoteConfigField("VALUE")]
        /// </summary>
        private string GetAttributeKeyFromSyntax(ISymbol member)
        {
            foreach (var syntaxRef in member.DeclaringSyntaxReferences)
            {
                var syntax = syntaxRef.GetSyntax();

                // Find attribute list - IMPORTANT: Fields use VariableDeclaratorSyntax
                SyntaxList<AttributeListSyntax> attributeLists = default;

                // ✅ FIX: For fields, the syntax is VariableDeclaratorSyntax, need to go up to FieldDeclarationSyntax
                if (syntax is VariableDeclaratorSyntax variableDeclarator)
                {
                    // Go up: VariableDeclaratorSyntax -> VariableDeclarationSyntax -> FieldDeclarationSyntax
                    if (variableDeclarator.Parent?.Parent is FieldDeclarationSyntax fieldDecl)
                    {
                        attributeLists = fieldDecl.AttributeLists;
                    }
                }
                else if (syntax is FieldDeclarationSyntax fieldSyntax)
                {
                    attributeLists = fieldSyntax.AttributeLists;
                }
                else if (syntax is PropertyDeclarationSyntax propertySyntax)
                {
                    attributeLists = propertySyntax.AttributeLists;
                }

                // Parse each attribute
                foreach (var attributeList in attributeLists)
                {
                    foreach (var attr in attributeList.Attributes)
                    {
                        var attrName = attr.Name.ToString();
                        if (attrName == "RemoteConfigField" || attrName == "RemoteConfigFieldAttribute")
                        {
                            if (attr.ArgumentList != null)
                            {
                                foreach (var arg in attr.ArgumentList.Arguments)
                                {
                                    // Case 1: Named argument [RemoteConfigField(Key = "VALUE")]
                                    if (arg.NameEquals != null && arg.NameEquals.Name.ToString() == "Key")
                                    {
                                        // ✅ FIX: Use LiteralExpressionSyntax to get actual value without quotes
                                        if (arg.Expression is LiteralExpressionSyntax literal)
                                        {
                                            return literal.Token.ValueText;
                                        }
                                        // Fallback: trim quotes manually
                                        return arg.Expression.ToString().Trim('"');
                                    }
                                    // Case 2: Constructor argument [RemoteConfigField("VALUE")]
                                    else if (arg.NameEquals == null && arg.Expression is LiteralExpressionSyntax literal)
                                    {
                                        return literal.Token.ValueText;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            return null;
        }

        private class ConfigMember
        {
            public string Name { get; set; }
            public string Type { get; set; }
            public string Key { get; set; }
        }

        private class RemoteConfigSyntaxReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
                    classDeclaration.AttributeLists.Count > 0)
                {
                    CandidateClasses.Add(classDeclaration);
                }
            }
        }
    }
}
